CREATE PROCEDURE [dbo].[spUpdateAppointmentModel]
    @Id INT,
    @TenantID INT,
    @UserID INT,
    @Subject NVARCHAR(50),
    @Description NVARCHAR(MAX),
    @StartTime DATETIME,
    @EndTime DATETIME,
    @TechnicianName NVARCHAR(50),
    @CustomerName NVARCHAR(50),
    @Location NVARCHAR(100),
    @Status INT,
    @IsAllDay BIT,
    @RecurrenceID INT,
    @RecurrenceRule NVARCHAR(200),
    @RecurrenceException NVARCHAR(200),
    @IsReadonly BIT,
    @IsBlock BIT,
    @CssClass NVARCHAR(50),
    @AvailableAppointmentId INT,
    @TenantName NVARCHAR(50),
    @CategoryColor NVARCHAR(10),
    @StartTimeZone NVARCHAR(50),
    @EndTimeZone NVARCHAR(50),
    
    @UpdatedAt DATETIME,
    @TechnicianId INT,
    @CustomerId INT,
    @ServiceID INT,
    @Deleted BIT,
    
    @JobTypeId INT
AS
BEGIN
    UPDATE Appointments
    SET TenantID = @TenantID,
        UserID = @UserID,
        Subject = @Subject,
        Description = @Description,
        StartTime = @StartTime,
        EndTime = @EndTime,
        TechnicianName = @TechnicianName,
        CustomerName = @CustomerName,
        Location = @Location,
        Status = @Status,
        IsAllDay = @IsAllDay,
        RecurrenceID = @RecurrenceID,
        RecurrenceRule = @RecurrenceRule,
        RecurrenceException = @RecurrenceException,
        IsReadonly = @IsReadonly,
        IsBlock = @IsBlock,
        CssClass = @CssClass,
        AvailableAppointmentId = @AvailableAppointmentId,
        TenantName = @TenantName,
        CategoryColor = @CategoryColor,
        StartTimeZone = @StartTimeZone,
        EndTimeZone = @EndTimeZone,
        
        UpdatedAt = @UpdatedAt,
        TechnicianId = @TechnicianId,
        CustomerId = @CustomerId,
        ServiceID = @ServiceID,
        Deleted = @Deleted,
        
        JobTypeId = @JobTypeId
    WHERE Id = @Id AND TenantID = @TenantID
END